### ISSUE TITLE
Add carthage.sh support

### ISSUE THREAD

**Issue by stason314** [rosberry/depo#11]
Depending on https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md

**Comment by zhvrnkov** [comment]
@stason314 you can use it like this. `depo carthage <some_command> --carthage-command-path <path_to_carthage.sh>`. For example, if `carthage.sh` is in your `PATH`, then just depo carthage <some_command> --carthage-command-path carthage.sh`
